name: Network Automation Workflow

on:
  push:
    branches:
      - Jit-dev

jobs:
  ospf_bgp_automation:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Run OSPF automation script
      - name: Run OSPF Config Script
        shell: powershell
        run: python .\ospf_config.py

      # Step 4: Run BGP automation script
      - name: Run BGP Config Script
        shell: powershell
        run: python .\BGPconfig.py
