name: BGP route consistency check Automation

on:
  push:
    branches: [ "Jit-dev" ]
  workflow_dispatch:   # allows manual trigger

jobs:
  run-network-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: BGP cli output parsing
        run: Parsing_BGP_Cli_output.py

      - name: Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: BGP_CLI_parsing logs
          path: BGP_Logs/
